# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "jellybeans"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  filemanager = "nerdtree"
  automatic_update = true

[[layers]]
  name = "autocomplete"
  autocomplete_method = "coc"
# auto_completion_return_key_behavior = "nil"
# auto_completion_tab_key_behavior = "smart"

[[layers]]
  name = "shell"
  default_position = "top"
  default_height = 30

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"

[[layers]]
  name = "lsp"
  filetypes = [
    "javascript",
    "typescript",
    "sh"
  ]

[[layers]]
  name = "sudo"

[[layers]]
  name = "tmux"
